### ISSUE TITLE
[Feature request]: auto-reload URL source video at regular interval

### ISSUE THREAD

**Issue by dv8472** [vzhd1701/gridplayer#62] opened 2022-07-08 10:54 UTC
### Suggestion

Watching URL live streams/web cams (e.g. from youtoube) often comes to a freeze after several hours.
Happens in most players I've tried, vlc, mpv, also including GridPlayer.
Refreshing/reloading it manually in the player usually helps.
Would be great, if GridPlayer could come up with somethin like "auto-reload interval" feature:
- be available both, in general settings, and for each frame too.
- auto-reload option (on/off) per each frame and their interval (s/m/h) are to be saved in playlist for each frame.
- if the interval won't be provided/saved by the playlist, then the one from general settings will take over, if feature is enabled (on/off).
- the auto-reload feature in general settings should be possible to be disable the feature entirely (affecting the one in frames as well), in case somebody doesn't want it.

**Comment by vzhd1701** [comment] 2022-07-08 11:02
Do you mean it freezes when the stream ends?

**Comment by dv8472** [comment] 2022-07-08 11:12
No, it's not that case.
If the stream ends, or the URL changes, then that's ok.
But I'm watching a lot of world/nature/airports web cams.
For example: https://www.youtube.com/watch?v=doqBgKIBBh8
And this URL hasn't changed for months, perhaps even years.
That stream usually never ends, except of outages.
So it's streaming 24/7 nonstop.
Nevertheless, as I said before, all streams (at least those from youtube I know about), are comming to a freeze after several hours.
It's not a bug in GridPlayer, because even vlc or mpv are behaving the same after several hours.
I don't know what exactly is causing it.
The proposed auto-reload with interval could be a solution, because I haven't found any alike in the vlc or mpv so far.

**Comment by vzhd1701** [comment] 2022-07-14 18:26
This seems like a temporary solution. I'll have to investigate the cause of this later. But for now you have an option to auto-reload live videos.
![Clipboard Image (1)](https://user-images.githubusercontent.com/5212766/179055466-3a0e07d3-e8fe-40f0-a8df-08f6c8447839.png)

**Comment by dv8472** [comment] 2022-07-15 05:11
Veeeeery nice, thank you very much!
I'm gonna test it, so I keep this open for the moment.


Why a temporary soluion? You never know when it can be useful to somebody else and at some different case. I would keep it in the app., default in Disabled state as you made it.
What is there to investigate? You mean the reason I provided, that the youtube streams freeze after some time? Have you ran into it too?

**Comment by vzhd1701** [comment] 2022-07-15 05:38
> What is there to investigate?

I mean if the stream freeze, then there is some underlying problem that should be fixed to avoid those freezes. Maybe the stream link expires and should be updated regularly in the background to avoid those freezes without reloading the whole video.

**Closed** 2023-05-19 09:28 UTC
Labels: enhancement
